# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name: Unit test CI

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v1
      - name: Run tests for routes
        working-directory: ./routes
        run: |
          pip install pipenv
          pip install httmock
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80
      - name: Run tests for users
        working-directory: ./users
        run: |
          pip install pipenv
          pip install httmock
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80
      - name: Run tests for posts
        working-directory: ./publications
        run: |
          pip install pipenv
          pip install httmock
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80
      - name: Run tests for Offers
        working-directory: ./ofertas
        run: |
          pip install pipenv
          pip install httmock
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80
          coverage report
